name: compound
channels:
#   - pyviz
  - conda-forge
dependencies:
  - jupyterlab<3.0.0
  - geopandas
#   - rtree
#   - bokeh
  - geoviews>=1.6
  - hvplot
  - pyproj
  - pip
  - shapely
  - geopy
  - panel
  - param
  - altair
  - folium
#   - bokeh
#   - matplotlib
#   - geopy
#   - descartes
#   - mapclassify
#   - iris
#   - xesmf
#   - ipympl
  - pip:
    - dbfread
    - ortools
    - openrouteservice
