name: compound
channels:
  # - pyviz
  - conda-forge
dependencies:
  - jupyterlab
  - jupyter-panel-proxy
  - geopandas
  - rtree
  - bokeh
  - geoviews
  - hvplot
  - pyproj
  - panel
  - pip
  - geopy
  - pip:
    - dbfread
